version: '3'
services:
  ubuntu:
    build: ./ubuntu
    restart: 'no'
    ports:
      - '${APACHE_PORT}:80'
    volumes:
      - '../:/var/www'
      - './php/php.ini:/etc/php/7.2/apache2/php.ini'
      - './php/php.ini:/etc/php/7.2/cli/php.ini'
      - './apache2/apache2.conf:/etc/apache2/apache2.conf'
      - './apache2/ports.conf:/etc/apache2/ports.conf'
      - './apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    links:
      - mysql
  mysql:
    image: 'mysql:5.7'
    restart: 'no'
    command:
      - '--sql_mode=NO_AUTO_CREATE_USER'
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/logs:/var/log/mysql'
      - './mysql/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: adminka
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - './phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
